# Generated by Django 5.1.5 on 2026-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='replacement_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(choices=[('no_return', 'No Return / No Replacement'), ('7_days', '7-Day Return'), ('10_days', '10-Day Return'), ('15_days', '15-Day Return'), ('30_days', '30-Day Return')], default='no_return', max_length=20),
        ),
    ]
