# Generated by Django 5.1.5 on 2026-02-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_replacement_allowed_product_return_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(choices=[('no_return', 'No Return Policy'), ('7_days', '7-Day Return'), ('10_days', '10-Day Return'), ('15_days', '15-Day Return'), ('30_days', '30-Day Return')], default='no_return', max_length=20),
        ),
    ]
